### ISSUE TITLE
Fix commodities for "Rayari McGrath Research Outpost"

### ISSUE THREAD

**Issue by Psychoboy** [EtienneLamoureux/sc-trade-tools#109]
This location shows Titanium when it does not have Rayari McGrath Research Outpost

**Comment by EtienneLamoureux** [comment]
Thank you for the report. Just to double-check, you're sure you were not actually at "Rayari Cantwell Research Outpost" in-game? As they are both on Clio, it's easy to get them confused. It's possible it's me who has it mixed up in the files though.

**Comment by EtienneLamoureux** [comment]
Similar to https://github.com/EtienneLamoureux/sc-trade-tools/issues/106

**Comment by Psychoboy** [comment]
I'll double check later today and report back
