### ISSUE TITLE
Orison Admin 3.15.1 inventory incorrect

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#111]
## Describe the bug
Website claims that the Orison Admin (Orison Municipal Services) terminal has Agricultural Supplies and Medical Supplies. Neither of these are available for purchase (or even listed) when visited.

## To Reproduce
In game: 1) Visit Orison Municipal Services on Providence Platform. 2) visit terminal, 3) see only scrap and waste.
On Site: 1) Visit https://sc-trade.tools/shops/Stanton%20%3E%20Crusader%20%3E%20Orison%20%3E%20Admin, 2) See AS and MS for sale.

## Expected behaviour
These should match live's terminal.

Additional note:
Site claims the travel time from Orison's TDD to Orison's Admin takes 19m 18s. Even in a worst case scenario, it won't take much more than 4 minutes to run from TDD to the tram, just miss it, wait for the next, fly to Providence Platform, run up to Orison Municipal Services, and open the terminal. I don't know why it's claiming a 20 minute travel time...

**Comment by EtienneLamoureux** [comment]
Thanks, I'll look into it.

As a side note, it's claiming 20 mins because the site always assume that you need to take a ship from point A to point B. So, in this particular case, it thinks you will buy commodities, take a ship, leave atmo and come back down to sell.

**Comment by Kjasi** [comment]
Sounds like an opportunity to optimize the algorithm when locations are at the same city/base/station.

**Comment by EtienneLamoureux** [comment]
Fixed Orison inventory
