### ISSUE TITLE
Fix the Mustang Alpha cargo capacity

### ISSUE THREAD

**Issue by athulin** [EtienneLamoureux/sc-trade-tools#112]
When I try the trade routes tool, I find that a Mustang Alpha is assumed to take 6 SCU of cargo. This seems to be what the official page (https://robertsspaceindustries.com/pledge/ships/mustang/Mustang-Alpha) says, yet my Mustang Alpha (purchased a week or so ago) has only 4 SCU present. 

So I would like to adjust cargo size to reality in order to compare trade routes. Yet, there does not seem to be any way to do so.
I imagine this mayalso be of general interest in cases where part of the cargo space is occupied. 

Suggestion: Consider allowing the user to select a smaller storage pool (perhaps on SCU level, perhaps even on sub-SCU level) that may be used for trade calculations

**Comment by EtienneLamoureux** [comment]
Thanks for pointing it out, I will fix the data!
