### ISSUE TITLE
Update prices using the UEX API

### ISSUE THREAD

**Issue by Jordak** [EtienneLamoureux/sc-trade-tools#116]
[UEX Corp](https://uexcorp.space/api.html) provides an API for getting price data. Anecdotally, it has always been more up-to-date than sc-trade-tools. It would be great if sc-trade-tools used this data.

You would probably want to cache the data. You shouldn't need to get too fancy, since UEX provides an endpoint that has all buy/sell data for all trade ports at once (https://portal.uexcorp.space/api/tradeports). Fetch all the price data from all locations at once on a batch job every 24 hours, and simply cache that result until the next batch job.

On a related note, I'd love to help out on this project. Any plans to make it open-source and allow pull requests?

**Comment by EtienneLamoureux** [comment]
Thanks for the suggestion, I'll take a look at that integration.

And unfortunately no, we do not plan to accept contributions at this time, but thanks for the interest!

**Comment by EtienneLamoureux** [comment]
We will be updating the tools' data using https://github.com/EtienneLamoureux/sc-trade-companion going forward. That application is open-source.

**Comment by EtienneLamoureux** [comment]
UEX API has been added as a data point
