### ISSUE TITLE
Update Construction Material

### ISSUE THREAD

**Issue by Tonono29** [EtienneLamoureux/sc-trade-tools#125]
## Is your feature request related to a problem? Please describe.

Now is posible  to get  contruction material salvaging, so  we need updat price and where to sell

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the report!

We hope to address this using community-submissions through our upcoming [companion application](https://github.com/EtienneLamoureux/sc-trade-companion#sc-trade-companion). If we can't manage to release this soon, I'll manually add the prices.

**Comment by EtienneLamoureux** [comment]
Prices have been added
