### ISSUE TITLE
How to contribute to the Recycled Material Composite listings?

### ISSUE THREAD

**Issue by Metalsiege** [EtienneLamoureux/sc-trade-tools#126]
## Describe the bug

Recycled Composite Materials fails to return any results. 
## To Reproduce

Select Recycled Composite Materials from dropdown and add 1 or more SCU. Then search.
## Expected behaviour

Expected behavior is to return any shops and the associated price.
## Screenshots

![RMC_None](https://github.com/EtienneLamoureux/sc-trade-tools/assets/14224184/c80670d7-b478-402f-bfb8-89ac85e0846c)

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the report!

As we cannot datamine anymore, we've rolled out [a companion application](https://github.com/EtienneLamoureux/sc-trade-companion) to help members of the community data-run for the platform. If some locations have incomplete listings, feel free to fill in the gaps!

That being said, some locations use a light yellow color palettes that is hard to read for the app. Feel free to post screenshots of those kiosks, with the location selected in the "location" dropdown, and I'll do my best to add the survey manually.
