### ISSUE TITLE
Shubin Mining Facility SCD-1 Stock available change 3.23.1

### ISSUE THREAD

**Issue by Z6vCxe7hBlQ2ziKY** [EtienneLamoureux/sc-trade-tools#129]
Trade Routes suggested I pick up Astatine at SCD-1 , it is not available at this location
SCD-1 SELLS the following 

BERYL
GOLD
QUARTZ
TUNGSTEN
CORUNDUM
WASTE
COPPER

**Comment by EtienneLamoureux** [comment]
Corrected the listings
