### ISSUE TITLE
Fix website/app intermittently not showing results

### ISSUE THREAD

**Issue by KComrade53** [EtienneLamoureux/sc-trade-tools#130]
## Describe the bug

Tables on pages such as trade routes and mining don't show results when viewing page with `Desktop site` enabled on an Android phone. 

Using Firefox browser

## To Reproduce

1. Go to one of the pages containing a table of data. 
2. Switch to desktop site mode
3. Results no longer work and submit button doesn't work

## Expected behaviour

Table populates but contains more data like when viewing from computer

## Screenshots

Mobile view:

![Screenshot_20240609_130401_Firefox.jpg](https://github.com/EtienneLamoureux/sc-trade-tools/assets/8879331/72671442-c3d7-4b23-8cd6-e3d37db1fc5e)

Desktop view:
![Screenshot_20240609_124909_Firefox.jpg](https://github.com/EtienneLamoureux/sc-trade-tools/assets/8879331/039b75e9-ee67-4b88-8822-19630aa30675)

Another example:
![Screenshot_20240609_130417_Firefox.jpg](https://github.com/EtienneLamoureux/sc-trade-tools/assets/8879331/250fdcfd-e965-4f46-acff-08d03ba3465c)

**Comment by EtienneLamoureux** [comment]
Fixed in https://github.com/EtienneLamoureux/sc-trade-tools/blob/master/CHANGELOG.md#814
