### ISSUE TITLE
Failed to Load Resources - POST 400 Bad Request

### ISSUE THREAD

**Issue by cmilheim** [EtienneLamoureux/sc-trade-tools#134]
## Describe the bug
There appear to be API failures from the web UI when looking up trade routes

## To Reproduce
Go to [SC Trade Routes](https://sc-trade.tools/trade-routes), select a ship and any initial investment, then click Submit.  Nothing will load.  Inspecting the page shows a failure to load resources and error 400 (Bad Request) from the POST methods.

## Expected behaviour
Suggested trade routes and their commodities would be displayed along with an estimate of costs and profits.

## Screenshots
![image](https://github.com/user-attachments/assets/4f0a3a89-ca69-4b02-8406-3a06208b084b)

**Comment by EtienneLamoureux** [comment]
You are most likely using n outdated version of the frontend: 
1. Can you try refreshing without cache (<kbd>CTRL</kbd>+<kbd>F5</kbd>) and trying again?
2. I will clear the server-side & CDN cache as a precaution
