### ISSUE TITLE
BUG: trade routes Investment over 100000000 no results no error

### ISSUE THREAD

**Issue by wkosmos** [EtienneLamoureux/sc-trade-tools#136]
## Describe the bug
`/trade-routes` Value for `Initial Investment` over 100,000,000 causes no results to be shown and no (user facing) error.

## To Reproduce
1. `trade-routes` page
2. reset
3. choose ship (any)
4. enter `Initial Investment` over 100000000 (100,000,000) 
5. no results ([100000001 no results](https://sc-trade.tools/trade-routes?q=%257B%2522ship%2522:%2522Hull%2520C%2522,%2522investment%2522:100000001,%2522itemName%2522:%2522Neon%2522,%2522itemQuantityInScu%2522:50,%2522smartFilters%2522:false,%2522itemTypes%2522:%255B%255D,%2522itemNames%2522:%255B%255D,%2522locationTypes%2522:%255B%255D,%2522locationNames%2522:%255B%255D,%2522factions%2522:%255B%255D,%2522avoidHiddenLocations%2522:false%257D), [100000000 with results](https://sc-trade.tools/trade-routes?q=%257B%2522ship%2522:%2522Hull%2520C%2522,%2522investment%2522:100000000,%2522itemName%2522:%2522Neon%2522,%2522itemQuantityInScu%2522:50,%2522smartFilters%2522:false,%2522itemTypes%2522:%255B%255D,%2522itemNames%2522:%255B%255D,%2522locationTypes%2522:%255B%255D,%2522locationNames%2522:%255B%255D,%2522factions%2522:%255B%255D,%2522avoidHiddenLocations%2522:false%257D))

## Expected behaviour
- show results 
- this is an intentional error (400: `{"investment":"must be less than or equal to 100000000"}` ), but has no corresponding UX
   - if non-temporary, include user-facing error message rather than blank/no results

**Comment by EtienneLamoureux** [comment]
Will be addressed in the 4.0 release :)
