### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by RommelTJ** [EtienneLamoureux/sc-trade-tools#27]
Hi @EtienneLamoureux,

Huge fan of sc-trade-tools. Stumbled upon the repo and its open issues and I was looking at ways I could contribute. Specifically, I was looking at [this issue](https://github.com/EtienneLamoureux/sc-trade-tools/issues/20) as a good intro to your codebase since I am fluent in Spanish. 

After looking at the repo, it looks like this is just a public issue repository. So my question is, where is the code and how do you envision community contributions into the repo? Thanks! o7

**Comment by EtienneLamoureux** [comment]
Hi @RommelTJ,

First of all, thank you for your interest in the project! It genuinely warms my heart to see such a question asked.

Unfortunately, SC Trade Tools is a closed-source project at this time. With sponsorship available through Patreon, I wouldn't feel comfortable using someone else's work. That being said, I might reconsider in the future. 

As for community contribution, at the moment everyone is encouraged to submit feature requests and bug reports for things they'd want to see!

Thanks again and 

**Keep on trading!**

**Comment by RommelTJ** [comment]
Thank you. I understand. I don't expect any kind of payment or credit from the Patreon. I am 100% comfortable with giving away the work for free so long as the tool remains open to use to me and my org :). I see it as a bonus that you are able to attract funds via Patreon. It means you are more likely to maintain it, which means any potential feature/bug-fix/translation/suggestion/etc contributions wouldn't be wasted. 

Thank you for your time and feel free to @ mention me if you change your mind!
