### ISSUE TITLE
Add maximum wait time option

### ISSUE THREAD

**Issue by zorbulator** [EtienneLamoureux/sc-trade-tools#29]
The "Allow wait times" option is great but I often find that most of the highest-profit routes have insanely long wait times. I think it would be useful to have an option to choose the maximum time you will wait so that the profit can be lowered to a more reasonable amount. This would mean that when sorting by highest profit it wouldn't be necessary to filter out most drugs and stations that buy slowly.

**Comment by zorbulator** [comment]
I was very surprised to see that this was already added two days after I suggested it, but the way it works might not be optimal in all situations... It works well for filtering out unreasonable routes but another use it could have would be to find trade routes that are still good even with the wait times. For example, using a Freelancer to sell Altruciatoxin at Grim HEX has a 26 minute wait time which is too long for it to be a useful route; if I were currently to set the maximum wait to 5 minutes, it would remove all of the possible routes involving Altruciatoxin. This isn't a super important change but if it instead limited the routes to 4,000 units instead of 6,600 the profit would still be high and the wait time would be eliminated.

**Comment by EtienneLamoureux** [comment]
Ah, I see what you mean! Partially full cargo. I'll add another item to track it independently!
