### ISSUE TITLE
Are refresh rates accurate?

### ISSUE THREAD

**Issue by zorbulator** [EtienneLamoureux/sc-trade-tools#37]
Since the economy was changed recently it seems to me like the refresh rates in game are slower than those on this website; it's possible that I'm misunderstanding the information on the website but when I wait a minute after a commodity runs out the amount available is much lower than the refresh rate per minute shown here.

## Is your feature request related to a problem? Please describe.

Obviously it's a pretty big problem if the trade routes don't actually work since not enough of a resource is available.
## Describe the solution you'd like

I don't know where the refresh rates came from originally but they should be updated to the new numbers.
## Describe alternatives you've considered

There aren't really any alternatives unless you are just going to shut down the website since trade is so bad now, but I think there might still be some decent routes but a website like this is necessary to find them

**Comment by EtienneLamoureux** [comment]
Hello and thanks for your feedback. The data comes straight from the 3.10.0s PTU game files. I'll check if the latest patch changed anything. 

One thing to note is that someone else may be buying the same commodity as you are at the same time on another server. 

If you could give me an example where the refresh rate seems widly different in the game from what you see in the trade tool, I'll gladly investigate!

**Comment by EtienneLamoureux** [comment]
Preliminary observation: other sites that pull from the data directly seem to agree with the current refresh rates (https://scunpacked.com/commodities). Should check further.

**Comment by EtienneLamoureux** [comment]
After verification, all refresh rates are accurate.
