### ISSUE TITLE
Fix maximum ship size allowed at grim hex

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#38]
## Describe the bug
I'm looking for profitable routes with my Caterpillar and Starfarer, and I keep getting Grim Hex in the list, even though it can't support landing a Size 5 ship there.

## To Reproduce
Set your ship to Caterpillar, Starfarer, or likely any size 5 ship, and look for a profitable trip. See that Grim Hex is in there.

## Expected behaviour
Grim Hex (and possibly a few other stations) aren't listed because the selected ship can't land there.

**Comment by EtienneLamoureux** [comment]
Hello and thanks for your feedback. The website does have the capability to exclude stations based on ship size.

The good news is that in 3.10, which is the version the website is updated to, grim hex does have xlarge hangars!

The workaround for now is to blacklist grim hex in the location filters. You can also simply "park" large ships near grim hex to sell there.
