### ISSUE TITLE
Are refresh rates accurate?

### ISSUE THREAD

**Issue by Spectrum888** [EtienneLamoureux/sc-trade-tools#43]
First of all thank you for making this site, it's amazing! Way better than Gallog.co. Anyway, it appears that the inventory refresh rate isn't correct for WiDow and Altruciatoxin at Grim. Currently it's listed as 10/min for WiDow and 100/min for Altruciatoxin but waiting at the terminal took 6-7 minutes before I was able to sell 362 Altruciatoxin (still had ~3k units left over) and 29 WiDow (all I had left). I waited for 5 more refreshes and was only able to sell 117/460/119/443/231 more units of Altruciatoxin (not sure why the numbers varied). There was a 30k so I connected to a fresh new server (only had 12 players) and after waiting 8 minutes i was able to sell 458 units. I'll do some more testing but that's what I've noticed so far. Neon seemed to sell at a rate much more consistent with what you have posted but I haven't timed it accurately yet. Haven't tried SLAM yet.

**Comment by zorbulator** [comment]
It's possible that this is caused by other people buying/selling at the same time as you but it's still a pretty major problem so it would be useful if this tool had some option to estimate the actual refresh rate or to filter out locations that are popular enough to not have stock

**Comment by Spectrum888** [comment]
> It's possible that this is caused by other people buying/selling at the same time as you but it's still a pretty major problem so it would be useful if this tool had some option to estimate the actual refresh rate or to filter out locations that are popular enough to not have stock

I was in the terminal room the whole time so I know I was the only one selling there. Not sure why the amount varied that much unless the inventory somehow is linked to other outposts or the server somehow dynamically changes refresh amount based on the frequency of sales.

**Comment by zorbulator** [comment]
I believe that with the recent changes to the economy stock is the same across all servers so people could be buying/selling on another server

**Comment by EtienneLamoureux** [comment]
First of all thank you for your feedback! I try to make SC Trade Tools as useful as possible and I greatly appreciate bug reports.
Now tot he question at hand. Zorbulator is correct: Inventory and refresh rates are shared across all servers, so all players must compete for the same stock. For example, if someone is hammering the buy button on another server, that could explain the seemingly random refresh rates you seem to have experienced. This will be much more frequent on high-demand commodities.
Nonetheless, I'll try to add a note to the refresh rates to explain this better, as currently it rightfully causes some confusion.

https://github.com/EtienneLamoureux/sc-trade-tools/issues/37
