### ISSUE TITLE
Fix 3.10 LIVE trading data

### ISSUE THREAD

**Issue by Gecko774** [EtienneLamoureux/sc-trade-tools#47]
Hi,
at first it is a very great Website and i really like to use it.
Good Work and looks great.

The problem actually is that at many stations you cant sell  or buy cargo who are displayed at your Site.

Astatine as Example can not sold at Rayari Kaltag Research Outpost.
There are many other goods and Stations where the same problem is.

Tested today
SC Version is 3.10 Live at EU and AUS Server today at 
21 PM.

Or is the Website for PTU and not Live?

Sry for my bad English ;)

**Comment by EtienneLamoureux** [comment]
Thank you for the feedback!

I'll look into it.

**Comment by EtienneLamoureux** [comment]
I double-checked an the data seems correct. The reason for the missing commodities is explained by [this new F.A.Q. entry](https://github.com/EtienneLamoureux/sc-trade-tools/blob/master/README.md#why-cant-i-buysell-a-commodity-where-the-website-says-I-should-be-able-to).
