### ISSUE TITLE
Correctly treat some special locations as hidden

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#50]
## Describe the bug
Stanton > microTech > Euterpe > Devlin Scrap & Salvage is being listed even when Avoid Hidden is active.

## Reproduction
Ship: Caterpillar
Starting Funds: 100000
Profit: Over Time
Min Refresh: 1000
Avoid Hidden: Active

5th one shown is "Stanton > microTech > Port Tressler > Admin" to "Stanton > microTech > Euterpe > Devlin Scrap & Salvage" for a profit of 28,800 UEC over 8m 49s.

## Expected behaviour
It should not be listed when Avoid Hidden is active.

**Comment by EtienneLamoureux** [comment]
Thanks for the report, I'll look into it!

**Comment by EtienneLamoureux** [comment]
Full list of affected locations:
- Stanton > microTech > Calliope > Raven's Roost
- Stanton > microTech > Euterpe > Devlin Scrap & Salvage
- Stanton > microTech > Outpost 54
