### ISSUE TITLE
How to get around, alleviate or fix inaccurate prices and refresh rates?

### ISSUE THREAD

**Issue by Vigger21** [EtienneLamoureux/sc-trade-tools#57]
These are supposedly from game files yet they are completely inaccurate and all over the place. This would be the best side for trading if it displayed actualised data.

**Comment by zorbulator** [comment]
Where did you experience the inaccurate information? Most of the previous issues about inaccurate game data were because people were buying or selling on other servers; are you sure that isn't the problem?

**Comment by EtienneLamoureux** [comment]
Thanks for the feedback. First of all, a quick explanation: 
> Why can't I buy/sell as much of a commodity as the website says I can?
> As the economy is global, it is shared across all servers. If someone else is or has been buying/selling the same commodity as you, the available stock will be lowered by that much. Since the data comes from the static game files, the tools will currently only report the total inventory and refresh rates. I hope to have dynamic stock details in the future.

> Why are the prices reported different from the ones in-game?
> The universe simulation makes the prices vary based on supply and demand. Since the data comes from the static game files, the tools will currently only report the most optimistic profit to be made. I hope have dynamic prices in the future.
- https://sc-trade.tools/home#faq

That being said, I understand the frustration: you get to a place and you can't buy what you were going for/don't make as much profit as expected. I'm trying to alleviate that in the next update with the following features: #8 #55
If you have other ideas on how to get around that issue, let me know!

**Comment by EtienneLamoureux** [comment]
I'd like to turn this into a design discussion about what would be a good solution to the problem, given the current limitations (can't hack into CIG's servers!). Brainstorm away!

**Comment by EtienneLamoureux** [comment]
Blocked by https://github.com/EtienneLamoureux/sc-trade-tools/issues/73
