### ISSUE TITLE
No Astatine at Shubin Mining Facility SM0-22

### ISSUE THREAD

**Issue by resteele02** [EtienneLamoureux/sc-trade-tools#58]
## Describe the bug
The Trade Tools site shows Astatine at Shubin Mining Facility SM0-22 but in game (PU 3.10.2) there is only Diamonds and no Astatine.

## To Reproduce
Look up trade routes for Astatine. The tool shows a purchase of Astatine at Shubin Mining Facility SM0-22 on MicroTech. But there is not any Astatine at the trade terminal at Shubin Mining Facility SM0-22 on MicroTech in the gaem

## Expected behaviour
The Trade Tools site shows Diamonds at Shubin Mining Facility SM0-22

## Screenshots
![image](https://user-images.githubusercontent.com/70445736/91642134-0b539b80-e9e6-11ea-9248-812a7292ac5f.png)

**Comment by resteele02** [comment]
Never mind. I'm an idiot and was at the wrong location in game.  LOL

**Comment by EtienneLamoureux** [comment]
No worries, it happens! 

Happy trading!
