### ISSUE TITLE
Add Best Seller page

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#60]
## Describe the solution you'd like
Add a page where you can specify a commodity and an (optional?) amount, and it will list all the locations that sells that item, plus all it's details. I want to look for a specific commodity, and see a list of all the places that sells it.

Literally, it's the Best buyer page, but for places that sells the specified item.

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the suggestion! I'll absorb this request with #59 and I'll keep a reference so I can come back here and check your comment.

In the meantime, you can get something similar to what you described by using the /trade-route tool and white listing only 1 commodity:
![image](https://user-images.githubusercontent.com/3357406/91723639-10d9ee80-eb6a-11ea-9edd-0c18e9d04494.png)

I know it's not the same, but I hope it somewhat does the trick while I start thinking about what you suggested!

**Comment by EtienneLamoureux** [comment]
Oh, one more question: what's your complete use-case? Why would you like to have all the sellers of a particular commodity?

**Comment by Kjasi** [comment]
The primary reason is finding alternate locations to buy up things I'm already trading. I'm at the stage of trading Laranite, but for the 2-3 places I see listed in the trade route, I've barely scratched the amount I can hold in my cargo deck. IE: I wanna trade a full Cat of Laranite, but I can only fill 29-86 SCU from a single location. I'm not getting anywhere NEAR the 320 SCU the trade route is asking me to buy. To try and get CLOSE, I have to go to multiple locations to buy more Laranite, but I'm only seeing 1 or two Laranite spots in the suggested trade routes. Seeing a full list would alleviate that, and I can make a trip out to those other locations in order to fill up my hold.

Another reason is research. I'm hearing other traders are saying "Oh, _this_ is a good trade" and I wanna see where those items would originate from. I can then compare that to the suggested trading route and make adjustments.

Maybe this could be handled a different way, but for the most part, I think this is the easiest way. I mean, at least from a web-perspective, you've already got the page up and running, you just need to swap the page title and the database/table you're pulling from.

**Comment by EtienneLamoureux** [comment]
Man versus the machine! I do believe my algorithms are producing the best trading routes, but I have nothing against letting people try to beat them by hand! I'll think of something scalable that fits with the rest of the tools. Thanks for the feedback and getting back to me.

For laranite in particular, most places only replenish ~13 SCU per minute of it. That's the reason why you almost never find any large quantities of the stuff. From a money making perspective, it's then more lucrative to trade another commodity than to go around multiple places trying to fill up on a single rare commodity. You can also try your hand at mixed cargo loads with the new "Alternative commodities" button. I made it to help me fill up when I go places and they don't have enough to load a full ship:

![image](https://user-images.githubusercontent.com/3357406/91853717-99bb5d80-ec30-11ea-97d9-51dc4a582fb2.png)

Again thanks for the feedback, I'll start drafting a solution.
