### ISSUE TITLE
Split the "Minimum refresh rate" filter into "buy" and "sell" rates

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/sc-trade-tools#61]

**Comment by SerethiX** [comment]
As a suggestion: Add maximum buy / sell rate.

Compare the buy rate of this shop with the sell rate of all producers. So you can filter out massively over produced commodities.

**Comment by EtienneLamoureux** [comment]
Refresh rate cannot be obtained anymore since the data-mineable info has been removed from the client.
