### ISSUE TITLE
Link Shop and Commodies pages

### ISSUE THREAD

**Issue by Kjasi** [EtienneLamoureux/sc-trade-tools#72]
## Describe the solution you'd like
When on the shop page, or the commodities page, I'd like to be able to click on the commodity's name to open the Commodity page for that item. Likewise, being able to open the shop's page for a shop listed in Commodity would also be helpful in designing my own routes.

Otherwise, I have to manually search for both on their respective pages, slowing me down.

**Comment by EtienneLamoureux** [comment]
That's easy enough and would be useful. Good idea.
