### ISSUE TITLE
Are the prices updated for 3.11?

### ISSUE THREAD

**Issue by ChaplainDamon** [EtienneLamoureux/sc-trade-tools#83]
So I have done several trade routes and lost out on some money because the Selling price of the goods was not the same as what the website says. For instance, I bought 3,083 units of Distilled Spirits from Gellet Family Farms @ 4.05 UEC each. I reach Port Tressler where the website says that I can sell them for a total of 17,480.61 UEC. I reach Port Tressler to sell my goods and see that I can only sell them for 14,860. 

Is there a way to know for sure that all prices are updated with 3.11 or am I just going to have to guess?

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the report. To make sure which version of Star Citizen is currently supported by the website, you can look at the green banner at the top of the homepage of visit [this URL](https://sc-trade.tools/api/system/sc-version). Now for the detailed answer: 

> Why are the prices reported different from the ones in-game?
> The universe simulation makes the prices vary based on supply and demand. Since the data comes from the static game files, the tools will currently only report the most optimistic profit to be made. I hope have dynamic prices in the future.
- https://sc-trade.tools/home#faq

First of all, I know this is frustrating, as I run into the issue myself when I trade. As an band-aid provisional solution, I've added price-per-unit when hovering on the aggregate buy and sell prices (see below). This should allow you to avoid buying commodities at an inflated price: simply compare the terminal price with the website price and if the price difference is too much, consider an alternative commodity.

![image](https://user-images.githubusercontent.com/3357406/95698237-4bc24e00-0c0f-11eb-8064-5b88540f9746.png)

Secondly, I do plan to have the prices update live from the servers' data, as planned in #73, but providing APIs to do so doesn't seem to be CIG's priority (see comment on linked issue). Unfortunately, as long as the APIs are not provided, trying to scrape the data in a unsupported way would break the game's TOS.

To somewhat alleviate the risk of running into low-supplied commodities (and therefore inflated prices), you can try visiting places with higher refresh rates.
