### ISSUE TITLE
New tool: /ores

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/sc-trade-tools#90]
Display the rich data about price, resistance, clustering factor, abundance by location and concentration by deposit or ores

**Comment by SerethiX** [comment]
It would be very useful to have spawn probabilities like [this](https://datastudio.google.com/reporting/bd9af7c8-708d-4fb1-9a6f-9ccf52a18cb4/page/uQomB?s=iGC2f1VySPQ)

Maybe directly linked with refineries and where to sell the refined ores.

**Comment by SerethiX** [comment]
Nevermind #87 is similiar, will those tools be linked together, so you can go from deposits to ores and vice versa?

**Comment by EtienneLamoureux** [comment]
@SerethiX There's already an "ore/deposit per planet" tool in the form of the /mining page. The /deposit would have even more detailed data: cluster size, clusters per volume, exact composition chances, etc.

The /ores page will be mostly static, as there's not as much data. They could be cross-linked like the /shops and /commodities pages though!
