### ISSUE TITLE
Display min/max prices and profits

### ISSUE THREAD

**Issue by SerethiX** [EtienneLamoureux/sc-trade-tools#96]
It would be really great to have the prices split into min and max buy and sell prices.

Also the profit should display a range. To save some space the price could be displayed as the median and on mouseover the min and max values show up.

This way the trader could make an even more informed trading decision.

**Comment by EtienneLamoureux** [comment]
This is a good idea. I'll try to crack the price vs inventory formula. I may need help with the prices of sold out items to figure out the extremes.

**Comment by EtienneLamoureux** [comment]
This is now part of #108
