### ISSUE TITLE
Reporting prices

### ISSUE THREAD

**Issue by SerethiX** [EtienneLamoureux/sc-trade-tools#97]
At first: I know of #73 and other tickets from the past, but I do not think, that this feautes get's implemented soon or in the way we think, since it would be OP.
In the meantime I want to propose a system that could work and even discourage false price reports.

The core would be a user based system. So any reporter is connected on the page via an account.
This account could be linked to the RSI-Account so it's less likely that this user messes with the prices. Verification would include setting a randomly generated string as the bio / short bio on the RSI-Website. This step would be mandatory.

All reported prices will be stored and visualized for the visitor, so fake reporters could be spotted easily by looking at "who is constantly reporting high buy and low sell prices".

Also the trader could read a trend of this chart and see when it's generally a good time to "trade x at y". When are a lot of other traders or when it's more quiet.

For the price that's used to calculate the trade routes the median or mean of the last x reported prices should be used, so every report moves the price more into the direction it is, but no individual can manipulate the system so it becomes unusable for the the rest.
The reporting could be limited by shop, so the user could report all commodities of a shop at once, then have a cooldown of x minutes until the next report + may contain a check of the travel distance. Let's say the user wants to report in Lorville but reported in Port Olisar a minute ago, the system would ignore his report silently, since he couldn't have made it in this time.
Another fraud protection would be to allow any value as the price, but check if it's in the possible range given by the game files and mark the user as fraudulent. They could get their very own price pools like cheaters get on servers with other cheaters in some games.

If it's possible and not too expensive on the CPU, user's should be able to ignore certain users to remove those reports from their own calculations, if they think they are wrong.

The price reports must include the region the player is in and the trade tools must get a filter for that aswell.

**Comment by EtienneLamoureux** [comment]
I will roll this up into #108 as it's more inline with the current road map for the project.
